# coding: utf-8

"""
PaymentvalidationApi.py
Copyright 2016 SmartBear Software

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
"""

from __future__ import absolute_import

import sys
import os

# python 2 and python 3 compatibility library
from six import iteritems

from ..configuration import Configuration
from ..api_client import ApiClient



class PaymentvalidationApi(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        config = Configuration()
        if api_client:
            self.api_client = api_client
        else:
            if not config.api_client:
                config.api_client = ApiClient()
            self.api_client = config.api_client


    def paymentvalidation(self, order_id, pay_pal_key, **kwargs):
        """
        Submit payment validation for PayPal
        Submit payment validation for PayPal

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>

        >>> thread = api.paymentvalidation(order_id, pay_pal_key, callback=callback_function)



        :param callback function: The callback function
            for asynchronous request. (optional)

        :param str order_id: Order Id returned from orders/POST (required)

        :param str pay_pal_key: The PayPal key returned from the Mobile SDK (required)

        :return: PaymentValidationResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['order_id', 'pay_pal_key']
        all_params.append('callback')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method paymentvalidation" % key
                )
            params[key] = val
        del params['kwargs']



        # verify the required parameter 'order_id' is set
        if ('order_id' not in params) or (params['order_id'] is None):
            raise ValueError("Missing the required parameter `order_id` when calling `paymentvalidation`")



        # verify the required parameter 'pay_pal_key' is set
        if ('pay_pal_key' not in params) or (params['pay_pal_key'] is None):
            raise ValueError("Missing the required parameter `pay_pal_key` when calling `paymentvalidation`")



        resource_path = '/paymentvalidation/'.replace('{format}', 'json')
        path_params = {}


        query_params = {}

        if 'order_id' in params:
            query_params['OrderId'] = params['order_id']

        if 'pay_pal_key' in params:
            query_params['PayPalKey'] = params['pay_pal_key']


        header_params = {}


        form_params = []
        local_var_files = {}


        body_params = None


        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])
        if not header_params['Accept']:
            del header_params['Accept']

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = []

        response = self.api_client.call_api(resource_path, 'GET',
                                            path_params,
                                            query_params,
                                            header_params,
                                            body=body_params,
                                            post_params=form_params,
                                            files=local_var_files,
                                            response_type='PaymentValidationResponse',
                                            auth_settings=auth_settings,
                                            callback=params.get('callback'))
        return response


