# coding: utf-8

"""
Copyright 2016 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Ref: https://github.com/swagger-api/swagger-codegen
"""

from pprint import pformat
from six import iteritems


class ShipOption(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        ShipOption - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'id': 'int',
            'method_type': 'str',
            'method_id': 'int',
            'name': 'str',
            'carrier_name': 'str',
            'carrier_logo_url': 'str',
            'price': 'ShipPrice',
            'est_business_days_til_delivery': 'int'
        }

        self.attribute_map = {
            'id': 'Id',
            'method_type': 'MethodType',
            'method_id': 'MethodId',
            'name': 'Name',
            'carrier_name': 'CarrierName',
            'carrier_logo_url': 'CarrierLogoUrl',
            'price': 'Price',
            'est_business_days_til_delivery': 'EstBusinessDaysTilDelivery'
        }

        self._id = None
        self._method_type = None
        self._method_id = None
        self._name = None
        self._carrier_name = None
        self._carrier_logo_url = None
        self._price = None
        self._est_business_days_til_delivery = None

    @property
    def id(self):
        """
        Gets the id of this ShipOption.
        The ID that can be passed into the /orders POST endpoing as ShipCarrierMethodId to specify an item's shipping method.

        :return: The id of this ShipOption.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this ShipOption.
        The ID that can be passed into the /orders POST endpoing as ShipCarrierMethodId to specify an item's shipping method.

        :param id: The id of this ShipOption.
        :type: int
        """
        self._id = id

    @property
    def method_type(self):
        """
        Gets the method_type of this ShipOption.


        :return: The method_type of this ShipOption.
        :rtype: str
        """
        return self._method_type

    @method_type.setter
    def method_type(self, method_type):
        """
        Sets the method_type of this ShipOption.


        :param method_type: The method_type of this ShipOption.
        :type: str
        """
        self._method_type = method_type

    @property
    def method_id(self):
        """
        Gets the method_id of this ShipOption.


        :return: The method_id of this ShipOption.
        :rtype: int
        """
        return self._method_id

    @method_id.setter
    def method_id(self, method_id):
        """
        Sets the method_id of this ShipOption.


        :param method_id: The method_id of this ShipOption.
        :type: int
        """
        self._method_id = method_id

    @property
    def name(self):
        """
        Gets the name of this ShipOption.


        :return: The name of this ShipOption.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this ShipOption.


        :param name: The name of this ShipOption.
        :type: str
        """
        self._name = name

    @property
    def carrier_name(self):
        """
        Gets the carrier_name of this ShipOption.


        :return: The carrier_name of this ShipOption.
        :rtype: str
        """
        return self._carrier_name

    @carrier_name.setter
    def carrier_name(self, carrier_name):
        """
        Sets the carrier_name of this ShipOption.


        :param carrier_name: The carrier_name of this ShipOption.
        :type: str
        """
        self._carrier_name = carrier_name

    @property
    def carrier_logo_url(self):
        """
        Gets the carrier_logo_url of this ShipOption.


        :return: The carrier_logo_url of this ShipOption.
        :rtype: str
        """
        return self._carrier_logo_url

    @carrier_logo_url.setter
    def carrier_logo_url(self, carrier_logo_url):
        """
        Sets the carrier_logo_url of this ShipOption.


        :param carrier_logo_url: The carrier_logo_url of this ShipOption.
        :type: str
        """
        self._carrier_logo_url = carrier_logo_url

    @property
    def price(self):
        """
        Gets the price of this ShipOption.


        :return: The price of this ShipOption.
        :rtype: ShipPrice
        """
        return self._price

    @price.setter
    def price(self, price):
        """
        Sets the price of this ShipOption.


        :param price: The price of this ShipOption.
        :type: ShipPrice
        """
        self._price = price

    @property
    def est_business_days_til_delivery(self):
        """
        Gets the est_business_days_til_delivery of this ShipOption.


        :return: The est_business_days_til_delivery of this ShipOption.
        :rtype: int
        """
        return self._est_business_days_til_delivery

    @est_business_days_til_delivery.setter
    def est_business_days_til_delivery(self, est_business_days_til_delivery):
        """
        Sets the est_business_days_til_delivery of this ShipOption.


        :param est_business_days_til_delivery: The est_business_days_til_delivery of this ShipOption.
        :type: int
        """
        self._est_business_days_til_delivery = est_business_days_til_delivery

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

