# coding: utf-8

"""
Copyright 2016 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Ref: https://github.com/swagger-api/swagger-codegen
"""

from pprint import pformat
from six import iteritems


class SubmittedOrderList(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        SubmittedOrderList - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'orders': 'list[SearchSubmittedOrder]',
            'total_pages': 'int',
            'page': 'int',
            'had_error': 'bool'
        }

        self.attribute_map = {
            'orders': 'Orders',
            'total_pages': 'TotalPages',
            'page': 'Page',
            'had_error': 'HadError'
        }

        self._orders = None
        self._total_pages = None
        self._page = None
        self._had_error = None

    @property
    def orders(self):
        """
        Gets the orders of this SubmittedOrderList.


        :return: The orders of this SubmittedOrderList.
        :rtype: list[SearchSubmittedOrder]
        """
        return self._orders

    @orders.setter
    def orders(self, orders):
        """
        Sets the orders of this SubmittedOrderList.


        :param orders: The orders of this SubmittedOrderList.
        :type: list[SearchSubmittedOrder]
        """
        self._orders = orders

    @property
    def total_pages(self):
        """
        Gets the total_pages of this SubmittedOrderList.


        :return: The total_pages of this SubmittedOrderList.
        :rtype: int
        """
        return self._total_pages

    @total_pages.setter
    def total_pages(self, total_pages):
        """
        Sets the total_pages of this SubmittedOrderList.


        :param total_pages: The total_pages of this SubmittedOrderList.
        :type: int
        """
        self._total_pages = total_pages

    @property
    def page(self):
        """
        Gets the page of this SubmittedOrderList.


        :return: The page of this SubmittedOrderList.
        :rtype: int
        """
        return self._page

    @page.setter
    def page(self, page):
        """
        Sets the page of this SubmittedOrderList.


        :param page: The page of this SubmittedOrderList.
        :type: int
        """
        self._page = page

    @property
    def had_error(self):
        """
        Gets the had_error of this SubmittedOrderList.


        :return: The had_error of this SubmittedOrderList.
        :rtype: bool
        """
        return self._had_error

    @had_error.setter
    def had_error(self, had_error):
        """
        Sets the had_error of this SubmittedOrderList.


        :param had_error: The had_error of this SubmittedOrderList.
        :type: bool
        """
        self._had_error = had_error

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

