# coding: utf-8

"""
OrdersearchApi.py
Copyright 2016 SmartBear Software

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
"""

from __future__ import absolute_import

import sys
import os

# python 2 and python 3 compatibility library
from six import iteritems

from ..configuration import Configuration
from ..api_client import ApiClient


class OrdersearchApi(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        config = Configuration()
        if api_client:
            self.api_client = api_client
        else:
            if not config.api_client:
                config.api_client = ApiClient()
            self.api_client = config.api_client

    def g_et_ordersearch(self, **kwargs):
        """
        Search an orders
        Search through the orders and return information about orders that match search criteria.

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.g_et_ordersearch(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str generic_values: Any value which is related to order (partner name, address, phone, couponCode, etc...)
        :param str last_name: Partner last name
        :param str email: Partner email
        :param str postal_code: Billing/Shipping address postal code
        :param str start_date: Start date of the date range when order was created
        :param str end_date: End date of the date range when order was created
        :param str unique_user_id: User Id
        :param int partner_id: Partner Id
        :param int page_size: How many items to return in reponse.
        :param int page: Page number, how many items to skip.
        :return: SubmittedOrderList
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['generic_values', 'last_name', 'email', 'postal_code', 'start_date', 'end_date', 'unique_user_id', 'partner_id', 'page_size', 'page']
        all_params.append('callback')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method g_et_ordersearch" % key
                )
            params[key] = val
        del params['kwargs']


        resource_path = '/ordersearch/'.replace('{format}', 'json')
        path_params = {}

        query_params = {}
        if 'generic_values' in params:
            query_params['genericValues'] = params['generic_values']
        if 'last_name' in params:
            query_params['lastName'] = params['last_name']
        if 'email' in params:
            query_params['email'] = params['email']
        if 'postal_code' in params:
            query_params['postalCode'] = params['postal_code']
        if 'start_date' in params:
            query_params['startDate'] = params['start_date']
        if 'end_date' in params:
            query_params['endDate'] = params['end_date']
        if 'unique_user_id' in params:
            query_params['uniqueUserId'] = params['unique_user_id']
        if 'partner_id' in params:
            query_params['partnerId'] = params['partner_id']
        if 'page_size' in params:
            query_params['pageSize'] = params['page_size']
        if 'page' in params:
            query_params['page'] = params['page']

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None

        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])
        if not header_params['Accept']:
            del header_params['Accept']

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = []

        response = self.api_client.call_api(resource_path, 'GET',
                                            path_params,
                                            query_params,
                                            header_params,
                                            body=body_params,
                                            post_params=form_params,
                                            files=local_var_files,
                                            response_type='SubmittedOrderList',
                                            auth_settings=auth_settings,
                                            callback=params.get('callback'))
        return response
