# coding: utf-8

"""
Copyright 2016 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Ref: https://github.com/swagger-api/swagger-codegen
"""



from pprint import pformat
from six import iteritems


class PaymentValidationRequest(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        PaymentValidationRequest - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'order_id': 'str',
            'pay_pal_key': 'str'
        }

        self.attribute_map = {
            'order_id': 'OrderId',
            'pay_pal_key': 'PayPalKey'
        }


        self._order_id = None

        self._pay_pal_key = None



    @property
    def order_id(self):
        """
        Gets the order_id of this PaymentValidationRequest.


        :return: The order_id of this PaymentValidationRequest.
        :rtype: str
        """
        return self._order_id

    @order_id.setter
    def order_id(self, order_id):
        """
        Sets the order_id of this PaymentValidationRequest.


        :param order_id: The order_id of this PaymentValidationRequest.
        :type: str
        """
        self._order_id = order_id


    @property
    def pay_pal_key(self):
        """
        Gets the pay_pal_key of this PaymentValidationRequest.


        :return: The pay_pal_key of this PaymentValidationRequest.
        :rtype: str
        """
        return self._pay_pal_key

    @pay_pal_key.setter
    def pay_pal_key(self, pay_pal_key):
        """
        Sets the pay_pal_key of this PaymentValidationRequest.


        :param pay_pal_key: The pay_pal_key of this PaymentValidationRequest.
        :type: str
        """
        self._pay_pal_key = pay_pal_key


    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other



