# coding: utf-8

"""
Copyright 2016 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Ref: https://github.com/swagger-api/swagger-codegen
"""



from pprint import pformat
from six import iteritems


class ProductPreviewImage(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        ProductPreviewImage - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'layer_id': 'str',
            'image': 'ProductPreviewImageSpec'
        }

        self.attribute_map = {
            'layer_id': 'LayerId',
            'image': 'Image'
        }


        self._layer_id = None

        self._image = None



    @property
    def layer_id(self):
        """
        Gets the layer_id of this ProductPreviewImage.


        :return: The layer_id of this ProductPreviewImage.
        :rtype: str
        """
        return self._layer_id

    @layer_id.setter
    def layer_id(self, layer_id):
        """
        Sets the layer_id of this ProductPreviewImage.


        :param layer_id: The layer_id of this ProductPreviewImage.
        :type: str
        """
        self._layer_id = layer_id


    @property
    def image(self):
        """
        Gets the image of this ProductPreviewImage.


        :return: The image of this ProductPreviewImage.
        :rtype: ProductPreviewImageSpec
        """
        return self._image

    @image.setter
    def image(self, image):
        """
        Sets the image of this ProductPreviewImage.


        :param image: The image of this ProductPreviewImage.
        :type: ProductPreviewImageSpec
        """
        self._image = image


    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other



