# coding: utf-8

"""
Copyright 2016 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Ref: https://github.com/swagger-api/swagger-codegen
"""



from pprint import pformat
from six import iteritems


class SearchSubmittedOrder(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        SearchSubmittedOrder - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'id': 'str',
            'nice_id': 'str',
            'source_id': 'str',
            'items': 'list[PostSubmittedItem]',
            'total': 'ProductPriceInfo',
            'shipping_total': 'ProductPriceInfo',
            'discount_code': 'str',
            'discount_amount': 'ProductPriceInfo',
            'meta': 'Meta'
        }

        self.attribute_map = {
            'id': 'Id',
            'nice_id': 'NiceId',
            'source_id': 'SourceId',
            'items': 'Items',
            'total': 'Total',
            'shipping_total': 'ShippingTotal',
            'discount_code': 'DiscountCode',
            'discount_amount': 'DiscountAmount',
            'meta': 'Meta'
        }


        self._id = None

        self._nice_id = None

        self._source_id = None

        self._items = None

        self._total = None

        self._shipping_total = None

        self._discount_code = None

        self._discount_amount = None

        self._meta = None



    @property
    def id(self):
        """
        Gets the id of this SearchSubmittedOrder.


        :return: The id of this SearchSubmittedOrder.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this SearchSubmittedOrder.


        :param id: The id of this SearchSubmittedOrder.
        :type: str
        """
        self._id = id


    @property
    def nice_id(self):
        """
        Gets the nice_id of this SearchSubmittedOrder.


        :return: The nice_id of this SearchSubmittedOrder.
        :rtype: str
        """
        return self._nice_id

    @nice_id.setter
    def nice_id(self, nice_id):
        """
        Sets the nice_id of this SearchSubmittedOrder.


        :param nice_id: The nice_id of this SearchSubmittedOrder.
        :type: str
        """
        self._nice_id = nice_id


    @property
    def source_id(self):
        """
        Gets the source_id of this SearchSubmittedOrder.
        Clients can submit an ID they use for the order here.

        :return: The source_id of this SearchSubmittedOrder.
        :rtype: str
        """
        return self._source_id

    @source_id.setter
    def source_id(self, source_id):
        """
        Sets the source_id of this SearchSubmittedOrder.
        Clients can submit an ID they use for the order here.

        :param source_id: The source_id of this SearchSubmittedOrder.
        :type: str
        """
        self._source_id = source_id


    @property
    def items(self):
        """
        Gets the items of this SearchSubmittedOrder.


        :return: The items of this SearchSubmittedOrder.
        :rtype: list[PostSubmittedItem]
        """
        return self._items

    @items.setter
    def items(self, items):
        """
        Sets the items of this SearchSubmittedOrder.


        :param items: The items of this SearchSubmittedOrder.
        :type: list[PostSubmittedItem]
        """
        self._items = items


    @property
    def total(self):
        """
        Gets the total of this SearchSubmittedOrder.


        :return: The total of this SearchSubmittedOrder.
        :rtype: ProductPriceInfo
        """
        return self._total

    @total.setter
    def total(self, total):
        """
        Sets the total of this SearchSubmittedOrder.


        :param total: The total of this SearchSubmittedOrder.
        :type: ProductPriceInfo
        """
        self._total = total


    @property
    def shipping_total(self):
        """
        Gets the shipping_total of this SearchSubmittedOrder.


        :return: The shipping_total of this SearchSubmittedOrder.
        :rtype: ProductPriceInfo
        """
        return self._shipping_total

    @shipping_total.setter
    def shipping_total(self, shipping_total):
        """
        Sets the shipping_total of this SearchSubmittedOrder.


        :param shipping_total: The shipping_total of this SearchSubmittedOrder.
        :type: ProductPriceInfo
        """
        self._shipping_total = shipping_total


    @property
    def discount_code(self):
        """
        Gets the discount_code of this SearchSubmittedOrder.


        :return: The discount_code of this SearchSubmittedOrder.
        :rtype: str
        """
        return self._discount_code

    @discount_code.setter
    def discount_code(self, discount_code):
        """
        Sets the discount_code of this SearchSubmittedOrder.


        :param discount_code: The discount_code of this SearchSubmittedOrder.
        :type: str
        """
        self._discount_code = discount_code


    @property
    def discount_amount(self):
        """
        Gets the discount_amount of this SearchSubmittedOrder.


        :return: The discount_amount of this SearchSubmittedOrder.
        :rtype: ProductPriceInfo
        """
        return self._discount_amount

    @discount_amount.setter
    def discount_amount(self, discount_amount):
        """
        Sets the discount_amount of this SearchSubmittedOrder.


        :param discount_amount: The discount_amount of this SearchSubmittedOrder.
        :type: ProductPriceInfo
        """
        self._discount_amount = discount_amount


    @property
    def meta(self):
        """
        Gets the meta of this SearchSubmittedOrder.
        An optional Map<string,string> of misc properties.

        :return: The meta of this SearchSubmittedOrder.
        :rtype: Meta
        """
        return self._meta

    @meta.setter
    def meta(self, meta):
        """
        Sets the meta of this SearchSubmittedOrder.
        An optional Map<string,string> of misc properties.

        :param meta: The meta of this SearchSubmittedOrder.
        :type: Meta
        """
        self._meta = meta


    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other



