# coding: utf-8

"""
Copyright 2016 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Ref: https://github.com/swagger-api/swagger-codegen
"""



from pprint import pformat
from six import iteritems


class ShipPrice(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        ShipPrice - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'price': 'int',
            'currency_code': 'str',
            'formatted_price': 'str'
        }

        self.attribute_map = {
            'price': 'Price',
            'currency_code': 'CurrencyCode',
            'formatted_price': 'FormattedPrice'
        }


        self._price = None

        self._currency_code = None

        self._formatted_price = None



    @property
    def price(self):
        """
        Gets the price of this ShipPrice.


        :return: The price of this ShipPrice.
        :rtype: int
        """
        return self._price

    @price.setter
    def price(self, price):
        """
        Sets the price of this ShipPrice.


        :param price: The price of this ShipPrice.
        :type: int
        """
        self._price = price


    @property
    def currency_code(self):
        """
        Gets the currency_code of this ShipPrice.


        :return: The currency_code of this ShipPrice.
        :rtype: str
        """
        return self._currency_code

    @currency_code.setter
    def currency_code(self, currency_code):
        """
        Sets the currency_code of this ShipPrice.


        :param currency_code: The currency_code of this ShipPrice.
        :type: str
        """
        self._currency_code = currency_code


    @property
    def formatted_price(self):
        """
        Gets the formatted_price of this ShipPrice.


        :return: The formatted_price of this ShipPrice.
        :rtype: str
        """
        return self._formatted_price

    @formatted_price.setter
    def formatted_price(self, formatted_price):
        """
        Sets the formatted_price of this ShipPrice.


        :param formatted_price: The formatted_price of this ShipPrice.
        :type: str
        """
        self._formatted_price = formatted_price


    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other



