# coding: utf-8

"""
Copyright 2016 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Ref: https://github.com/swagger-api/swagger-codegen
"""

from pprint import pformat
from six import iteritems


class Shipment(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        Shipment - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'tracking_number': 'str',
            'tracking_url': 'str',
            'ship_carrier_name': 'str'
        }

        self.attribute_map = {
            'tracking_number': 'TrackingNumber',
            'tracking_url': 'TrackingUrl',
            'ship_carrier_name': 'ShipCarrierName'
        }

        self._tracking_number = None
        self._tracking_url = None
        self._ship_carrier_name = None

    @property
    def tracking_number(self):
        """
        Gets the tracking_number of this Shipment.


        :return: The tracking_number of this Shipment.
        :rtype: str
        """
        return self._tracking_number

    @tracking_number.setter
    def tracking_number(self, tracking_number):
        """
        Sets the tracking_number of this Shipment.


        :param tracking_number: The tracking_number of this Shipment.
        :type: str
        """
        self._tracking_number = tracking_number

    @property
    def tracking_url(self):
        """
        Gets the tracking_url of this Shipment.


        :return: The tracking_url of this Shipment.
        :rtype: str
        """
        return self._tracking_url

    @tracking_url.setter
    def tracking_url(self, tracking_url):
        """
        Sets the tracking_url of this Shipment.


        :param tracking_url: The tracking_url of this Shipment.
        :type: str
        """
        self._tracking_url = tracking_url

    @property
    def ship_carrier_name(self):
        """
        Gets the ship_carrier_name of this Shipment.


        :return: The ship_carrier_name of this Shipment.
        :rtype: str
        """
        return self._ship_carrier_name

    @ship_carrier_name.setter
    def ship_carrier_name(self, ship_carrier_name):
        """
        Sets the ship_carrier_name of this Shipment.


        :param ship_carrier_name: The ship_carrier_name of this Shipment.
        :type: str
        """
        self._ship_carrier_name = ship_carrier_name

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

